version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "80:80"
  database:
    container_name: database
    build: ./database/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  backend:
    container_name: backend
    build: ./backend/
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
      